/* DetourEats v0.4 sample route data
   Simulated corridor: Amsterdam, NY → Myrtle Beach, SC
   These are prototype candidates, not live verified recommendations.
*/

const candidates = [
  {
    id: "heritage-diner",
    seq: 1,
    name: "Heritage Diner",
    category: "Breakfast / Diner",
    chain: false,
    estimatedAddedMinutes: 6,
    foodReputation: 78,
    destinationWorthiness: 70,
    uniqueness: 62,
    reviewConfidence: 82,
    consistency: 78,
    famousFor: "scratch pancakes and strong coffee",
    evidenceSummary: "Reliable local breakfast without much added time.",
    arrivalClock: "8:45 AM",
    openAtArrival: true
  },
  {
    id: "maple-street-biscuit-house",
    seq: 2,
    name: "Maple Street Biscuit House",
    category: "Breakfast / Southern",
    chain: false,
    estimatedAddedMinutes: 11,
    foodReputation: 91,
    destinationWorthiness: 88,
    uniqueness: 82,
    reviewConfidence: 87,
    consistency: 84,
    famousFor: "buttermilk biscuits and sausage gravy",
    evidenceSummary: "The kind of breakfast stop that feels like part of the trip.",
    arrivalClock: "9:20 AM",
    openAtArrival: true
  },
  {
    id: "riverbend-bagels",
    seq: 3,
    name: "Riverbend Bagels",
    category: "Breakfast / Coffee",
    chain: false,
    estimatedAddedMinutes: 4,
    foodReputation: 76,
    destinationWorthiness: 64,
    uniqueness: 58,
    reviewConfidence: 78,
    consistency: 80,
    famousFor: "fast egg sandwiches and house bagels",
    evidenceSummary: "Quick practical breakfast stop.",
    arrivalClock: "9:55 AM",
    openAtArrival: true
  },
  {
    id: "old-canal-smokehouse",
    seq: 4,
    name: "Old Canal Smokehouse",
    category: "BBQ",
    chain: false,
    estimatedAddedMinutes: 13,
    foodReputation: 95,
    destinationWorthiness: 94,
    uniqueness: 89,
    reviewConfidence: 91,
    consistency: 88,
    famousFor: "brisket, ribs, and cornbread",
    evidenceSummary: "A true destination-style BBQ stop if timing works.",
    arrivalClock: "11:40 AM",
    openAtArrival: true
  },
  {
    id: "hillside-tacos",
    seq: 5,
    name: "Hillside Tacos",
    category: "Mexican",
    chain: false,
    estimatedAddedMinutes: 8,
    foodReputation: 87,
    destinationWorthiness: 82,
    uniqueness: 80,
    reviewConfidence: 84,
    consistency: 83,
    famousFor: "al pastor tacos and fresh salsa",
    evidenceSummary: "Good lunch decision with low trip cost.",
    arrivalClock: "12:15 PM",
    openAtArrival: true
  },
  {
    id: "turnpike-grill",
    seq: 6,
    name: "Turnpike Grill",
    category: "American",
    chain: false,
    estimatedAddedMinutes: 5,
    foodReputation: 72,
    destinationWorthiness: 61,
    uniqueness: 54,
    reviewConfidence: 70,
    consistency: 76,
    famousFor: "burgers and quick service",
    evidenceSummary: "Not special, but convenient and acceptable.",
    arrivalClock: "12:55 PM",
    openAtArrival: true
  },
  {
    id: "county-line-pizza",
    seq: 7,
    name: "County Line Pizza",
    category: "Pizza",
    chain: false,
    estimatedAddedMinutes: 9,
    foodReputation: 84,
    destinationWorthiness: 78,
    uniqueness: 71,
    reviewConfidence: 80,
    consistency: 82,
    famousFor: "thin crust pies and garlic knots",
    evidenceSummary: "Solid local stop when lunch timing hits here.",
    arrivalClock: "1:35 PM",
    openAtArrival: true
  },
  {
    id: "blue-ridge-bbq",
    seq: 8,
    name: "Blue Ridge BBQ",
    category: "BBQ",
    chain: false,
    estimatedAddedMinutes: 18,
    foodReputation: 98,
    destinationWorthiness: 98,
    uniqueness: 92,
    reviewConfidence: 94,
    consistency: 90,
    famousFor: "pulled pork, ribs, and banana pudding",
    evidenceSummary: "Rare route-defining stop, but it asks for more time.",
    arrivalClock: "2:20 PM",
    openAtArrival: true
  },
  {
    id: "elm-street-cafe",
    seq: 9,
    name: "Elm Street Cafe",
    category: "Cafe",
    chain: false,
    estimatedAddedMinutes: 7,
    foodReputation: 81,
    destinationWorthiness: 72,
    uniqueness: 68,
    reviewConfidence: 78,
    consistency: 83,
    famousFor: "soups, sandwiches, and pies",
    evidenceSummary: "Good practical stop when you do not want a heavy meal.",
    arrivalClock: "3:05 PM",
    openAtArrival: true
  },
  {
    id: "market-house-kitchen",
    seq: 10,
    name: "Market House Kitchen",
    category: "Southern / Lunch",
    chain: false,
    estimatedAddedMinutes: 10,
    foodReputation: 90,
    destinationWorthiness: 87,
    uniqueness: 84,
    reviewConfidence: 86,
    consistency: 85,
    famousFor: "fried chicken sandwich and collards",
    evidenceSummary: "Strong regional food without a painful detour.",
    arrivalClock: "3:50 PM",
    openAtArrival: true
  },
  {
    id: "highway-chain-burger",
    seq: 11,
    name: "Highway Burger Chain",
    category: "Fast Food",
    chain: true,
    estimatedAddedMinutes: 3,
    foodReputation: 62,
    destinationWorthiness: 40,
    uniqueness: 20,
    reviewConfidence: 90,
    consistency: 78,
    famousFor: "standard burgers",
    evidenceSummary: "Chain fallback; hidden by default.",
    arrivalClock: "4:15 PM",
    openAtArrival: true
  },
  {
    id: "carolina-fish-camp",
    seq: 12,
    name: "Carolina Fish Camp",
    category: "Seafood",
    chain: false,
    estimatedAddedMinutes: 14,
    foodReputation: 94,
    destinationWorthiness: 93,
    uniqueness: 88,
    reviewConfidence: 90,
    consistency: 87,
    famousFor: "fried shrimp, hushpuppies, and slaw",
    evidenceSummary: "A memorable regional stop as the trip gets farther south.",
    arrivalClock: "5:35 PM",
    openAtArrival: true
  },
  {
    id: "farm-table-supper",
    seq: 13,
    name: "Farm Table Supper",
    category: "Dinner / Local",
    chain: false,
    estimatedAddedMinutes: 16,
    foodReputation: 92,
    destinationWorthiness: 90,
    uniqueness: 91,
    reviewConfidence: 84,
    consistency: 80,
    famousFor: "seasonal plates and local vegetables",
    evidenceSummary: "Great dinner candidate if the timing lines up.",
    arrivalClock: "6:25 PM",
    openAtArrival: true
  },
  {
    id: "oak-smoke-tavern",
    seq: 14,
    name: "Oak Smoke Tavern",
    category: "BBQ / Dinner",
    chain: false,
    estimatedAddedMinutes: 9,
    foodReputation: 88,
    destinationWorthiness: 84,
    uniqueness: 80,
    reviewConfidence: 82,
    consistency: 83,
    famousFor: "smoked wings and mac and cheese",
    evidenceSummary: "Strong dinner stop with low added time.",
    arrivalClock: "7:05 PM",
    openAtArrival: true
  },
  {
    id: "late-night-noodle",
    seq: 15,
    name: "Late Night Noodle",
    category: "Asian / Late Bite",
    chain: false,
    estimatedAddedMinutes: 12,
    foodReputation: 86,
    destinationWorthiness: 80,
    uniqueness: 82,
    reviewConfidence: 78,
    consistency: 79,
    famousFor: "spicy noodles and dumplings",
    evidenceSummary: "Useful late-trip option if dinner gets pushed.",
    arrivalClock: "8:10 PM",
    openAtArrival: true
  },
  {
    id: "closed-legend",
    seq: 16,
    name: "The Closed Legend",
    category: "BBQ",
    chain: false,
    estimatedAddedMinutes: 7,
    foodReputation: 99,
    destinationWorthiness: 99,
    uniqueness: 95,
    reviewConfidence: 94,
    consistency: 92,
    famousFor: "legendary ribs",
    evidenceSummary: "Would be perfect, but it is closed at arrival.",
    arrivalClock: "8:45 PM",
    openAtArrival: false
  }
];

window.DETOUR_EATS_CANDIDATES = candidates;
