/* DetourEats v0.5 curated real-route prototype
   Corridor: Amsterdam, NY → Myrtle Beach, SC
   Restaurant identities, addresses, published hours, and menu specialties are
   sourced from current official sites or current authoritative tourism/editorial sources.

   IMPORTANT:
   - Route position and added trip time are editorial estimates for prototype testing.
   - They are NOT live navigation calculations.
   - Detour Score is DetourEats editorial judgment, not a restaurant rating.
*/

const candidates = [
  {
    id: "brooks-house-bbq",
    seq: 1,
    name: "Brooks' House of BBQ",
    city: "Oneonta, NY",
    address: "5560 State Highway 7, Oneonta, NY 13820",
    category: "BBQ",
    chain: false,
    estimatedAddedMinutes: 10,
    estimateLabel: "Estimated",
    foodReputation: 89,
    destinationWorthiness: 86,
    uniqueness: 84,
    reviewConfidence: 90,
    consistency: 87,
    famousFor: "charcoal-pit barbecue chicken, ribs, brisket, and pulled pork",
    evidenceSummary: "Long-running regional barbecue institution with a distinctive charcoal-pit identity.",
    arrivalClock: "9:35 AM",
    openAtArrival: false,
    publishedHours: "Sun, Tue–Thu 11 AM–7 PM; Fri–Sat 11 AM–8 PM; Monday closed",
    verifiedDate: "July 2026",
    confidence: "High",
    sourceType: "Official restaurant website",
    sourceUrl: "https://brooksbbq.com/our-menu/",
    mapsUrl: "https://www.google.com/maps/search/?api=1&query=Brooks%27+House+of+BBQ+Oneonta+NY"
  },
  {
    id: "park-diner-binghamton",
    seq: 2,
    name: "Park Diner & Restaurant",
    city: "Binghamton, NY",
    address: "119 Conklin Ave, Binghamton, NY 13903",
    category: "Diner / Breakfast",
    chain: false,
    estimatedAddedMinutes: 7,
    estimateLabel: "Estimated",
    foodReputation: 79,
    destinationWorthiness: 72,
    uniqueness: 67,
    reviewConfidence: 83,
    consistency: 82,
    famousFor: "classic diner breakfast, sandwiches, and a riverfront setting",
    evidenceSummary: "A practical independent breakfast or early-lunch stop that is open when the trip reaches Binghamton.",
    arrivalClock: "10:35 AM",
    openAtArrival: true,
    publishedHours: "Mon–Sat 7 AM–8:30 PM; Sun 7 AM–3 PM",
    verifiedDate: "July 2026",
    confidence: "High",
    sourceType: "Official restaurant website",
    sourceUrl: "https://www.theparkdinerandrestaurant.com/",
    mapsUrl: "https://www.google.com/maps/search/?api=1&query=Park+Diner+and+Restaurant+Binghamton+NY"
  },

  {
    id: "krumpes-donuts",
    seq: 3,
    name: "Krumpe's Do-Nut Shop",
    city: "Hagerstown, MD",
    address: "912 Maryland Avenue, Hagerstown, MD",
    category: "Donuts / Late Bite",
    chain: false,
    estimatedAddedMinutes: 9,
    estimateLabel: "Estimated",
    foodReputation: 88,
    destinationWorthiness: 87,
    uniqueness: 91,
    reviewConfidence: 88,
    consistency: 86,
    famousFor: "an old-school evening-only doughnut stop",
    evidenceSummary: "An 80-plus-year Hagerstown tradition with unusual evening hours.",
    arrivalClock: "12:20 PM",
    openAtArrival: false,
    publishedHours: "Daily 7 PM–11 PM; holiday hours may differ",
    verifiedDate: "July 2026",
    confidence: "High",
    sourceType: "Official restaurant website",
    sourceUrl: "https://krumpesdonuts.com/",
    mapsUrl: "https://www.google.com/maps/search/?api=1&query=Krumpe%27s+Do-Nut+Shop+Hagerstown+MD"
  },
  {
    id: "bonnie-blue",
    seq: 4,
    name: "Bonnie Blue Southern Market & Bakery",
    city: "Winchester, VA",
    address: "334 W Boscawen St, Winchester, VA 22601",
    category: "Southern / BBQ / Bakery",
    chain: false,
    estimatedAddedMinutes: 13,
    estimateLabel: "Estimated",
    foodReputation: 92,
    destinationWorthiness: 90,
    uniqueness: 88,
    reviewConfidence: 91,
    consistency: 88,
    famousFor: "smoked meats, Southern plates, biscuits, and baked goods",
    evidenceSummary: "Strong regional identity and broad meal usefulness, from breakfast through barbecue.",
    arrivalClock: "1:10 PM",
    openAtArrival: true,
    publishedHours: "Mon–Thu 8 AM–4 PM; Fri 8 AM–8 PM; Sat–Sun 8 AM–4 PM",
    verifiedDate: "July 2026",
    confidence: "High",
    sourceType: "Official restaurant website",
    sourceUrl: "https://winchestersbestbbq.com/",
    mapsUrl: "https://www.google.com/maps/search/?api=1&query=Bonnie+Blue+Southern+Market+Winchester+VA"
  },
  {
    id: "edelweiss-staunton",
    seq: 5,
    name: "Edelweiss German Restaurant",
    city: "Staunton, VA",
    address: "19 Edelweiss Lane, Staunton, VA 24401",
    category: "German",
    chain: false,
    estimatedAddedMinutes: 8,
    estimateLabel: "Estimated",
    foodReputation: 90,
    destinationWorthiness: 89,
    uniqueness: 94,
    reviewConfidence: 87,
    consistency: 84,
    famousFor: "schnitzel, German specialties, Black Forest cake, and German beer",
    evidenceSummary: "Distinctive regional road-trip stop that offers something genuinely different.",
    arrivalClock: "3:00 PM",
    openAtArrival: true,
    publishedHours: "Tue–Sun 11 AM–9 PM; Monday closed",
    verifiedDate: "July 2026",
    confidence: "High",
    sourceType: "Official restaurant website",
    sourceUrl: "https://edelweissvirginia.com/",
    mapsUrl: "https://www.google.com/maps/search/?api=1&query=Edelweiss+German+Restaurant+Staunton+VA"
  },
  {
    id: "zzq-richmond",
    seq: 7,
    name: "ZZQ Texas Craft Barbeque",
    city: "Richmond, VA",
    address: "3201 W Moore St, Richmond, VA 23230",
    category: "Texas BBQ",
    chain: false,
    estimatedAddedMinutes: 17,
    estimateLabel: "Estimated",
    foodReputation: 97,
    destinationWorthiness: 97,
    uniqueness: 92,
    reviewConfidence: 94,
    consistency: 91,
    famousFor: "Texas-style beef brisket and craft barbecue",
    evidenceSummary: "A true destination-style stop, but hours and sellout risk matter.",
    arrivalClock: "5:00 PM",
    openAtArrival: true,
    publishedHours: "Wed–Sat 11 AM–6 PM; Sun 11 AM–5 PM; unless sold out",
    verifiedDate: "July 2026",
    confidence: "High",
    sourceType: "Official restaurant website",
    sourceUrl: "https://www.zzqrva.com/",
    mapsUrl: "https://www.google.com/maps/search/?api=1&query=ZZQ+Texas+Craft+Barbeque+Richmond+VA",
    operationalRisk: "May sell out before posted closing time"
  },
  {
    id: "parkers-wilson",
    seq: 9,
    name: "The Original Parker's Barbecue",
    city: "Wilson, NC",
    address: "2514 US Hwy 301 South, Wilson, NC 27896",
    category: "Eastern NC BBQ",
    chain: false,
    estimatedAddedMinutes: 11,
    estimateLabel: "Estimated",
    foodReputation: 91,
    destinationWorthiness: 89,
    uniqueness: 89,
    reviewConfidence: 92,
    consistency: 90,
    famousFor: "Eastern North Carolina barbecue, fried chicken, hushpuppies, and house-made sides",
    evidenceSummary: "Classic regional barbecue with broad hours and easy road-trip utility.",
    arrivalClock: "12:05 PM",
    openAtArrival: true,
    publishedHours: "Daily: dine-in 9 AM–7 PM; takeout 9 AM–7:30 PM",
    verifiedDate: "July 2026",
    confidence: "High",
    sourceType: "Official restaurant website",
    sourceUrl: "https://parkersbbqwilson.com/",
    mapsUrl: "https://www.google.com/maps/search/?api=1&query=Original+Parker%27s+Barbecue+Wilson+NC",
    operationalRisk: "Official site says cash or check only"
  },
  {
    id: "mccabes-manning",
    seq: 11,
    name: "McCabe's Bar-B-Q",
    city: "Manning, SC",
    address: "480 N Brooks St, Manning, SC 29102",
    category: "South Carolina BBQ",
    chain: false,
    estimatedAddedMinutes: 14,
    estimateLabel: "Estimated",
    foodReputation: 96,
    destinationWorthiness: 96,
    uniqueness: 95,
    reviewConfidence: 89,
    consistency: 88,
    famousFor: "Pee Dee whole-hog barbecue, fried chicken, hash and rice, and chicken bog",
    evidenceSummary: "A serious regional barbecue destination with very limited operating hours.",
    arrivalClock: "2:15 PM",
    openAtArrival: false,
    publishedHours: "Limited lunch service; current sources indicate Thursday–Saturday only",
    verifiedDate: "July 2026",
    confidence: "Medium",
    sourceType: "South Carolina tourism and current editorial sources",
    sourceUrl: "https://discoversouthcarolina.com/articles/100-mile-barbecue-mccabes-bar-b-que-in-manning",
    mapsUrl: "https://www.google.com/maps/search/?api=1&query=McCabe%27s+Bar-B-Q+Manning+SC",
    operationalRisk: "Limited days and hours; cash-only reports; verify before routing"
  },
  {
    id: "johnny-ds-myrtle",
    seq: 13,
    name: "Johnny D's Waffles and Benedicts",
    city: "Myrtle Beach, SC",
    address: "3301 North Kings Hwy, Myrtle Beach, SC 29577",
    category: "Breakfast / Brunch",
    chain: false,
    estimatedAddedMinutes: 6,
    estimateLabel: "Estimated",
    foodReputation: 89,
    destinationWorthiness: 84,
    uniqueness: 86,
    reviewConfidence: 88,
    consistency: 86,
    famousFor: "creative waffles, Benedicts, chicken and waffles, and brunch dishes",
    evidenceSummary: "A strong arrival-day breakfast or brunch choice at the destination.",
    arrivalClock: "9:00 AM",
    openAtArrival: true,
    publishedHours: "Current published social information indicates daily breakfast/lunch service",
    verifiedDate: "July 2026",
    confidence: "Medium",
    sourceType: "Official restaurant website and current official social information",
    sourceUrl: "https://www.johnnydswaffles.com/",
    mapsUrl: "https://www.google.com/maps/search/?api=1&query=Johnny+D%27s+Waffles+Myrtle+Beach+SC"
  }
];

window.DETOUR_EATS_CANDIDATES = candidates;
